---
- name: Download Wordpress
  become: true
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  become: true
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Update default Apache site
  become: true
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: "{{ item.regexp }}"
    line  : "{{ item.line }}"
    backrefs: yes
  with_items:
    - {'regexp': "(.)+DocumentRoot /var/www/html", 'line': "DocumentRoot /var/www/wordpress"}
  notify:
    - restart apache

- name: Copy sample config file
  become: true
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: Update WordPress config file
  become: true
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
    
- name: View japanese lang
  become: true
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    line: "define('WPLANG', 'ja');"
  notify:
    - restart apache

